openapi: 3.0.3
info:
  title: Payments API Documentation
  version: 1.1.0
servers:
  - url: http://127.0.0.1:5000
    description: Development Server
  - url: http://192.4.8.1:5000
    description: Production Server
paths: {}
