route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: 'ankit@thebrokenapp.in'
        from: 'ankit@thebrokenapp.in'
        smarthost: smtp.gmail.com:587
        auth_username: ankit@thebrokenapp.in
        auth_identity: xxxxxxx
        auth_password: xxxxxxxxxxxxxxx
